# version: '3.7'

services:
  rqlite-node1:
    image: rqlite/rqlite:latest
    ports:
      - "4001:4001"
      - "4002:4002"
    volumes:
      - ./backup-node1:/root/backup
      - rqlite-node1-data:/rqlite/file/data
    command: ["-node-id", "node1", "-http-addr", "0.0.0.0:4001", "-raft-addr", "0.0.0.0:4002", "-raft-log-level=INFO"]

  rqlite-node2:
    image: rqlite/rqlite:latest
    ports:
      - "4003:4001"
      - "4004:4002"
    volumes:
      - ./backup-node2:/root/backup
      - rqlite-node2-data:/rqlite/file/data
    command: ["-node-id", "node2", "-http-addr", "0.0.0.0:4001", "-raft-addr", "0.0.0.0:4002", "-join", "rqlite-node1:4002"]

  rqlite-node3:
    image: rqlite/rqlite:latest
    ports:
      - "4005:4001"
      - "4006:4002"
    volumes:
      - ./backup-node3:/root/backup
      - rqlite-node3-data:/rqlite/file/data
    # entrypoint: tail -f /dev/null
    command: ["-node-id", "node3", "-http-addr", "0.0.0.0:4001", "-raft-addr", "0.0.0.0:4002", "-join", "rqlite-node1:4002"]

volumes:
  rqlite-node1-data:
  rqlite-node2-data:
  rqlite-node3-data:
